check50:
    files:
        - !exclude "*"
        - !include "dictionary.txt"
        - !require hangman.py
        - !require test_hangman.py
        - !require schuifpuzzel.py
        - !require test_schuifpuzzel.py
